//
// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#import "GSCXScannerTestCase.h"

#import <XCTest/XCTest.h>

#import "third_party/objective_c/EarlGreyV2/TestLib/EarlGreyImpl/EarlGrey.h"
#import "GSCXContinuousScannerGalleryViewController.h"
#import "GSCXScannerResultDetailViewController.h"
#import "GSCXScannerScreenshotViewController.h"
#import "GSCXTestAppDelegate.h"
#import "GSCXTestReportViewController.h"
#import "GSCXTestScannerViewController.h"
#import "GSCXTestSharingDelegate.h"
#import "GSCXTestUIAccessibilityElementViewController.h"
#import "third_party/objective_c/GSCXScanner/Tests/FunctionalTests/Utils/GSCXScannerTestUtils.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * Offset from the origin at which to tap the third ring view. Tapping the origin fails because
 * it taps on the edge of the third ring view, which isn't considered inside the ring's frame.
 */
static const CGPoint kGSCXTestOverlappingRingViewTapOffset = {10, 10};

/**
 * The title of the button used to dismiss the share scan report action sheet before iOS 13.
 */
NSString *const kGSCXTestCancelShareReportButtonTitlePreIOS13 = @"Cancel";

/**
 * The accessibility label of the button used to dismiss the share scan report action sheet at and
 * after iOS 13.
 */
NSString *const kGSCXTestCancelShareReportButtonAccessibilityLabelPostIOS13 = @"Close";

@interface GSCXScannerTests : GSCXScannerTestCase

/**
 * Taps the share button to share a report of the scan.
 */
- (void)gscxtest_tapShareReportButton;

/**
 * Taps the cancel button to dismiss the share report action sheet. Because this is a system action
 * sheet, there is no way to access or set the accessibility identifier, so the title of the button,
 * Cancel, is used instead.
 */
- (void)gscxtest_tapCancelShareReportButton;

/**
 * Selects the ring view at the given index by matching the accessibility identifier generated by
 * + [GSCXScannerScreenshotViewController accessibilityIdentifierForRingViewAtIndex:].
 *
 * @param index The index of the ring view to be matched.
 * @return The result of selecting the given ring view.
 */
- (GREYElementInteraction *)gscxtest_selectRingViewAtIndex:(NSInteger)index;

/**
 * Selects a navigation bar button item with the given accessibility label and taps it.
 *
 * @param accessibilityLabel The accessibility label of the bar button item.
 */
- (void)gscxtest_tapBackButtonWithAccessibilityLabel:(NSString *)accessibilityLabel;

/**
 * Asserts that there are exactly the given number of rings on screen.
 *
 * @param count The exact number of rings that must exist to pass the test.
 */
- (void)gscxtest_assertRingViewCount:(NSInteger)count;

@end

@implementation GSCXScannerTests

- (void)testScanWithNoIssuesShowsAlert {
  [GSCXScannerTestUtils tapPerformScanButton];
  [GSCXScannerTestUtils dismissNoIssuesAlert];
}

- (void)testScanRootViewsWithAccessibilityIssuesPresentsScreenshot {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [[EarlGrey selectElementWithMatcher:grey_text(@"4 Issues")] assertWithMatcher:grey_notNil()];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testScreenshotPresentsRingViews {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [self gscxtest_assertRingViewCount:3];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testTappingOnRingViewWithMultipleIssuesPresentsGalleryView {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [[self gscxtest_selectRingViewAtIndex:0]
      assertWithMatcher:grey_accessibilityLabel(
                            @"2 issues for element with accessibility label Fail Checks 1 and 4")];
  [[self gscxtest_selectRingViewAtIndex:0] performAction:grey_tap()];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName1 isSufficientlyVisible:YES];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName2 isSufficientlyVisible:NO];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName3 isSufficientlyVisible:NO];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName4 isSufficientlyVisible:YES];
  [self gscxtest_tapBackButtonWithAccessibilityLabel:@"4 Issues"];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testTappingOnRingViewWithSingleIssuePresentsGalleryView {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [[self gscxtest_selectRingViewAtIndex:1]
      assertWithMatcher:grey_accessibilityLabel(
                            @"1 issue for element with accessibility label Fails Check 2")];
  [[self gscxtest_selectRingViewAtIndex:1] performAction:grey_tap()];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName1 isSufficientlyVisible:NO];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName2 isSufficientlyVisible:YES];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName3 isSufficientlyVisible:NO];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName4 isSufficientlyVisible:NO];
  [self gscxtest_tapBackButtonWithAccessibilityLabel:@"4 Issues"];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testTappingOnOverlappingRingViewsEachWithSingleIssueGalleryViewForFirstIndex {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [[self gscxtest_selectRingViewAtIndex:2]
      assertWithMatcher:
          grey_accessibilityLabel(
              @"1 issue for element with accessibility label Fails Check 3 and Overlaps")];
  [[self gscxtest_selectRingViewAtIndex:2]
      performAction:grey_tapAtPoint(kGSCXTestOverlappingRingViewTapOffset)];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName1 isSufficientlyVisible:NO];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName2 isSufficientlyVisible:YES];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName3 isSufficientlyVisible:NO];
  [self gscxtest_assertLabelForCheckNamed:kGSCXTestCheckName4 isSufficientlyVisible:NO];
  [self gscxtest_tapBackButtonWithAccessibilityLabel:@"4 Issues"];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testGalleryViewCanBeSwipedThrough {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [[self gscxtest_selectRingViewAtIndex:1] performAction:grey_tap()];
  [[self gscxtest_selectRingViewAtIndex:1] assertWithMatcher:grey_sufficientlyVisible()];
  [self gscxtest_swipeToPreviousGalleryPage];
  [[self gscxtest_selectRingViewAtIndex:0] assertWithMatcher:grey_sufficientlyVisible()];
  [self gscxtest_swipeToNextGalleryPage];
  [[self gscxtest_selectRingViewAtIndex:1] assertWithMatcher:grey_sufficientlyVisible()];
  [self gscxtest_swipeToNextGalleryPage];
  [[self gscxtest_selectRingViewAtIndex:2] assertWithMatcher:grey_sufficientlyVisible()];
  [self gscxtest_tapBackButtonWithAccessibilityLabel:@"4 Issues"];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testUIAccessibilityElementFailsCheck {
  [GSCXScannerTestUtils openPage:[GSCXTestUIAccessibilityElementViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [self gscxtest_assertRingViewCount:2];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testShareButtonPresentsActionSheetWithASCIIContent {
  [GSCXScannerTestUtils openPage:[GSCXTestScannerViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [self gscxtest_tapShareReportButton];
  [self gscxtest_tapCancelShareReportButton];
  [GSCXScannerTestUtils dismissScreenshotView];
}

- (void)testShareButtonPresentsActionSheetWithUTF8Content {
  [GSCXScannerTestUtils openPage:[GSCXTestReportViewController class]];
  [GSCXScannerTestUtils tapPerformScanButton];
  [self gscxtest_tapShareReportButton];
  [self gscxtest_tapCancelShareReportButton];
  [GSCXScannerTestUtils dismissScreenshotView];
}

#pragma mark - Private

- (void)gscxtest_tapShareReportButton {
  [[EarlGrey
      selectElementWithMatcher:grey_accessibilityID(kGSCXShareReportButtonAccessibilityIdentifier)]
      performAction:grey_tap()];
}

- (void)gscxtest_tapCancelShareReportButton {
  [[EarlGrey selectElementWithMatcher:[self gscxtest_matcherForCancelShareReportButton]]
      performAction:grey_tap()];
}

/**
 * @return A @c GREYMatcher instance that matches the button closing an activity view controller.
 */
- (id<GREYMatcher>)gscxtest_matcherForCancelShareReportButton {
  return grey_text(kGSCXTestSharingDelegateAlertDismissTitle);
}

- (GREYElementInteraction *)gscxtest_selectRingViewAtIndex:(NSInteger)index {
  NSString *ringViewAXId =
      [GSCXScannerScreenshotViewController accessibilityIdentifierForRingViewAtIndex:index];
  return [EarlGrey selectElementWithMatcher:grey_accessibilityID(ringViewAXId)];
}

/**
 * Swipes the gallery detail scroll view to the previous page.
 */
- (void)gscxtest_swipeToPreviousGalleryPage {
  [[EarlGrey
      selectElementWithMatcher:grey_accessibilityID(
                                   kGSCXContinuousScannerGalleryDetailViewAccessibilityIdentifier)]
      performAction:grey_swipeFastInDirection(kGREYDirectionRight)];
}

/**
 * Swipes the gallery detail scroll view to the next page.
 */
- (void)gscxtest_swipeToNextGalleryPage {
  [[EarlGrey
      selectElementWithMatcher:grey_accessibilityID(
                                   kGSCXContinuousScannerGalleryDetailViewAccessibilityIdentifier)]
      performAction:grey_swipeFastInDirection(kGREYDirectionLeft)];
}

- (void)gscxtest_tapBackButtonWithAccessibilityLabel:(NSString *)accessibilityLabel {
  id<GREYMatcher> matcher = grey_allOf(
      grey_ancestor(grey_keyWindow()), grey_ancestor(grey_kindOfClass([UINavigationBar class])),
      grey_ancestor(grey_accessibilityTrait(UIAccessibilityTraitButton)),
      grey_text(accessibilityLabel), nil);
  [[EarlGrey selectElementWithMatcher:matcher] performAction:grey_tap()];
}

- (void)gscxtest_assertRingViewCount:(NSInteger)count {
  for (NSInteger i = 0; i < count - 1; i++) {
    [[self gscxtest_selectRingViewAtIndex:i] assertWithMatcher:grey_notNil()];
  }
  [[self gscxtest_selectRingViewAtIndex:count] assertWithMatcher:grey_nil()];
}

/**
 * @return @c YES if the operating system is at iOS 13.0 or later, @c NO otherwise.
 */
- (BOOL)gscxtest_isAtLeastVersionIOS13 {
  if (@available(iOS 13, *)) {
    return YES;
  } else {
    return NO;
  }
}

/**
 * Asserts that a label with text equal to @c checkName is either sufficiently visible or not
 * sufficiently visible.
 *
 * @param checkName The text of the label to search for.
 * @param isSufficientlyVisible @c YES to assert the element is sufficiently visible, @c NO to
 * assert the element is not sufficiently visible.
 */
- (void)gscxtest_assertLabelForCheckNamed:(NSString *)checkName
                    isSufficientlyVisible:(BOOL)isSufficientlyVisible {
  id<GREYMatcher> matcher =
      isSufficientlyVisible ? grey_sufficientlyVisible() : grey_not(grey_sufficientlyVisible());
  [[EarlGrey selectElementWithMatcher:grey_text(checkName)] assertWithMatcher:matcher];
}

@end

NS_ASSUME_NONNULL_END
